# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '35 3 * * *'

jobs:
  stale:
    
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        days-before-stale: 1
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue does not have any recent activity and is thus considered stale. It will be closed soon, given that there is no activity.'
        stale-pr-message: 'This pull reques does not have any recent activity and is thus considered stale. It will be closed soon, given that there is no activity.'
        stale-issue-label: 'Stale'
        stale-pr-label: 'Stale'
